module.exports = {
var santi = [
	"Sant'Ambrogio",
	"San Francesco Saverio",
	"Sant'Antonio",
	"San Giuseppe",
	"San Francesco",
	"San Giorgio",
	"San Riccardo",
	"San Vincenzo",
	"Sant'Euplio",
	"Maria Vergine",
	"Maria di Cleofa",
	"Papa Adeodato I",
	"Papa Adriano III",
	"Papa Agapito I",
	"Papa Agatone",
	"Papa Anacleto",
	"Papa Anastasio I",
	"Papa Antero",
	"Papa Benedetto II",
	"Papa Bonifacio I",
	"Papa Bonifacio IV",
	"Papa Caio",
	"Papa Callisto I",
	"Papa Celestino I",
	"Papa Celestino V",
	"Papa Clemente I",
	"Papa Cornelio",
	"Papa Damaso I",
	"Papa Dionisio",
	"Papa Eleuterio",
	"Papa Eusebio",
	"Papa Eutichiano",
	"Papa Evaristo",
	"Papa Fabiano",
	"Papa Felice I",
	"Papa Felice III",
	"Papa Felice IV",
	"Papa Gelasio I",
	"Papa Gelasio II",
	"Papa Giovanni I",
	"Papa Giovanni Paolo II",
	"Papa Giovanni XXIII",
	"Papa Giulio I",
	"Papa Gregorio I",
	"Papa Gregorio II",
	"Papa Gregorio III",
	"Papa Gregorio VII",
	"Papa Igino",
	"Papa Ilario",
	"Papa Innocenzo I",
	"Papa Leone I",
	"Papa Leone II",
	"Papa Leone III",
	"Papa Leone IV",
	"Papa Leone IX",
	"Papa Lino",
	"Papa Lucio I",
	"Papa Marcellino",
	"Papa Marcello I",
	"Papa Marco",
	"Papa Martino I",
	"Papa Milziade",
	"Papa NiccolÃ² I",
	"Papa Ormisda",
	"Papa Paolo I",
	"Papa Paolo VI",
	"Papa Pasquale I",
	"Papa Pio I",
	"Papa Pio V",
	"Papa Pio X",
	"Papa Ponziano",
	"Papa Silverio",
	"Papa Silvestro I",
	"Papa Simmaco",
	"Papa Simplicio",
	"Papa Siricio",
	"Papa Sisto I",
	"Papa Sisto II",
	"Papa Sisto III",
	"Papa Sotero",
	"Papa Stefano I",
	"Papa Telesforo",
	"Papa Urbano I",
	"Papa Vitaliano",
	"Papa Zaccaria",
	"Papa Zefirino",
	"Papa Zosimo",
	"Protomartiri Francescani",
	"Samuele",
	"San Babila",
	"San Barbato di Benevento",
	"San Barlaam di Antiochia",
	"San Barnaba",
	"San Bartolomeo apostolo",
	"San Bartolomeo di Simeri",
	"San Bartolomeo il Giovane",
	"San Basilio Magno",
	"San Basilio di Ancira",
	"San Basino di Treviri",
	"San Bassiano",
	"San Bavone di Gand",
	"San Beda il Venerabile",
	"San Benedetto Giuseppe Labre",
	"San Benedetto Menni",
	"San Benedetto d'Aniane",
	"San Benedetto da Norcia",
	"San Benedetto di Hermillon",
	"San Benedetto di Milano",
	"San Benedetto il Moro",
	"San Benildo RomanÃ§on",
	"San Bennone",
	"San Berardo dei Marsi",
	"San Berardo di Teramo",
	"San Bercario",
	"San Bernardino Realino",
	"San Bernardino da Siena",
	"San Bernardo Tolomei",
	"San Bernardo da Corleone",
	"San Bernardo degli Uberti",
	"San Bernardo di Aosta",
	"San Bernardo di Chiaravalle",
	"San Bernardo di Tiron",
	"San Bernoardo di Hildesheim",
	"San Besso",
	"San Biagio",
	"San Birino di Dorchester",
	"San Bonaventura da Bagnoregio",
	"San Bonifacio vescovo",
	"San Brendano di Cluain Ferta",
	"San Brizio di Tours",
	"San Bruno di Colonia",
	"San Bruno di Segni",
	"San Bruno di Wurzburg",
	"San Brunone Bonifacio di Querfurt",
	"San Calidonio",
	"San Callisto Caravario",
	"San Calogero di Brescia",
	"San Calogero di Sicilia",
	"San Camillo De Lellis",
	"San Canuto IV",
	"San Canuto Lavard",
	"San Caprasio di LÃ©rins",
	"San Caritone",
	"San Carlo Borromeo",
	"San Carlo Eugenio de Mazenod",
	"San Carlo Lwanga",
	"San Carlo da Sezze",
	"San Carlo di sant'Andrea Houben",
	"San Casimiro",
	"San Cataldo",
	"San Cedda",
	"San Cesario di Arles",
	"San Cesario di Nazianzo",
	"San Charbel Makhlouf",
	"San Ciarano",
	"San Ciriaco di Gerusalemme",
	"San Cirillo di Alessandria",
	"San Cirillo di Gerusalemme",
	"San Cirillo",
	"San Claude de la ColombiÃ¨re",
	"San Claudio di Condat",
	"San Clemente Maria Hofbauer",
	"San Cleofa",
	"San Clodoaldo",
	"San Clodolfo di Metz",
	"San Colombano",
	"San Columba di Iona",
	"San Corbiniano",
	"San Corentino di Quimper",
	"San Cornelio il centurione",
	"San Corrado Birndorfer da Parzham",
	"San Corrado Confalonieri",
	"San Costantino",
	"San Costanzo di Perugia",
	"San Crisogono",
	"San Crispino da Viterbo",
	"San Cristoforo Magallanes",
	"San Crodegango di Metz",
	"San Cromazio",
	"San Cucufate",
	"San Cuniberto di Colonia",
	"San Cutberto di Lindisfarne",
	"San Damiano de Veuster",
	"San Daniele Comboni",
	"San Daniele di Bangor",
	"San David di Menevia",
	"San Davide Enrico Lewis",
	"San Demetrio di Tessalonica",
	"San Desiderio di Langres",
	"San Desiderio di Vienne",
	"San Diego d'AlcalÃ¡",
	"San Dionigi l'Areopagita",
	"San Dionisio di Alessandria",
	"San Domenico Savio",
	"San Domenico di Guzman",
	"San Domenico di Silos",
	"San Donato d'Arezzo",
	"San Donato di Fiesole",
	"San Donaziano di Reims",
	"San Dunstano di Canterbury",
	"San Faustino dell'Incarnazione",
	"San Fedele da Sigmaringen",
	"San Fedele di Como",
	"San Felice da Cantalice",
	"San Felice di Burgundia",
	"San Felice di Como",
	"San Felice di Nola",
	"San Felice di Valois",
	"San Ferdinando III",
	"San Ferreolo di Vienne",
	"San Filastrio",
	"San Filippo Benizi",
	"San Filippo Evans",
	"San Filippo Howard",
	"San Filippo Neri",
	"San Filippo Smaldone",
	"San Filippo apostolo",
	"San Filippo diacono",
	"San Filogonio",
	"San Firmino di Amiens",
	"San Flaviano di Costantinopoli",
	"San Flaviano",
	"San Floriano di Lorch",
	"San Fortunato di Todi",
	"San Francesco Antonio Fasani",
	"San Francesco Borgia",
	"San Francesco Caracciolo",
	"San Francesco De Geronimo",
	"San Francesco Fogolla",
	"San Francesco Maria da Camporosso",
	"San Francesco Regis Clet",
	"San Francesco Saverio Maria Bianchi",
	"San Francesco Saverio",
	"San Francesco Solano",
	"San Francesco d'Assisi",
	"San Francesco di Paola",
	"San Francesco di Sales",
	"San Francisco Marto",
	"San Franco da Assergi",
	"San Fridolino",
	"San Frodoino",
	"San Frumenzio",
	"San Fulberto di Chartres",
	"San Fulcranno di Lodeve",
	"San Gabriele arcangelo",
	"San Gabriele dell'Addolorata",
	"San Gaetano Catanoso",
	"San Gaetano Errico",
	"San Gaetano di Thiene",
	"San Galgano",
	"San Gallo",
	"San Gaspare Luigi Bertoni",
	"San Gaspare del Bufalo",
	"San Gaudenzio di Novara",
	"San Gaudioso di Brescia",
	"San Genebaldo di Laon",
	"San Gennaro",
	"San Geraldo D'Aurillac",
	"San Gerardo Maiella",
	"San Gerardo Sagredo",
	"San Gerardo di Brogne",
	"San Gerasimo",
	"San Gerlando di Agrigento",
	"San Germano I di Costantinopoli",
	"San Germano d'Auxerre",
	"San Germano di Capua",
	"San Geronzio di Cervia",
	"San GesÃ¹ Mendez Montoya",
	"San Giacinto Odrovaz",
	"San Giacomo Chastan",
	"San Giacomo della Marca",
	"San Giacomo di Osroena",
	"San Giacomo il Minore",
	"San Giacomo il maggiore",
	"San Giacomo l'Interciso",
	"San Giocondo di Aosta",
	"San Giorgio Preca",
	"San Giorgio",
	"San Giosafat Kuncewycz",
	"San Giovanni Almond",
	"San Giovanni Antonio Farina",
	"San Giovanni Battista Piamarta",
	"San Giovanni Battista de La Salle",
	"San Giovanni Battista de Rossi",
	"San Giovanni Battista della Concezione",
	"San Giovanni Battista",
	"San Giovanni Berchmans",
	"San Giovanni Bono",
	"San Giovanni Bosco",
	"San Giovanni Calabria",
	"San Giovanni Calibita",
	"San Giovanni Cassiano",
	"San Giovanni Climaco",
	"San Giovanni Crisostomo",
	"San Giovanni Damasceno",
	"San Giovanni Eudes",
	"San Giovanni Fisher",
	"San Giovanni Francesco RÃ©gis",
	"San Giovanni Gabriele Perboyre",
	"San Giovanni Giuseppe della Croce",
	"San Giovanni Gualberto",
	"San Giovanni Leonardi",
	"San Giovanni Maria Vianney",
	"San Giovanni Nepomuceno Neumann",
	"San Giovanni Nepomuceno",
	"San Giovanni Ogilvie",
	"San Giovanni Rigby",
	"San Giovanni Sarkander",
	"San Giovanni Theristis",
	"San Giovanni d'Avila",
	"San Giovanni da Capestrano",
	"San Giovanni da Dukla",
	"San Giovanni da Kety",
	"San Giovanni da Lodi",
	"San Giovanni da Matera",
	"San Giovanni da San Facondo",
	"San Giovanni da TraÃ¹",
	"San Giovanni da Triora",
	"San Giovanni de BrÃ©beuf",
	"San Giovanni de Matha",
	"San Giovanni de Ribera",
	"San Giovanni della Croce",
	"San Giovanni di Beverley",
	"San Giovanni di Dio",
	"San Giovanni di Rila",
	"San Giovanni evangelista",
	"San Giovanni il Silenziario",
	"San Giovanni l'Elemosiniere",
	"San Giovenale di Narni",
	"San Girolamo Emiliani",
	"San Girolamo",
	"San Giuda Taddeo",
	"San Giuliano Saba",
	"San Giuliano di Toledo",
	"San Giuliano l'ospitaliere",
	"San Giuliano martire",
	"San Giulio d'Orta",
	"San Giuseppe Benedetto Cottolengo",
	"San Giuseppe Cafasso",
	"San Giuseppe Calasanzio",
	"San Giuseppe Freinademetz",
	"San Giuseppe Marello",
	"San Giuseppe Maria Rubio Peralta",
	"San Giuseppe Maria Tomasi",
	"San Giuseppe Maria de Yermo y Parres",
	"San Giuseppe Moscati",
	"San Giuseppe Pignatelli",
	"San Giuseppe Sebastiano Pelczar",
	"San Giuseppe d'Arimatea",
	"San Giuseppe da Copertino",
	"San Giuseppe da Leonessa",
	"San Giuseppe l'Innografo",
	"San Giuseppe",
	"San Giustino Martire",
	"San Giustino de Jacobis",
	"San Giusto di Canterbury",
	"San Giusto di Trieste",
	"San Glicerio di Milano",
	"San Glisente",
	"San Godescalco",
	"San Goffredo di Cappenberg",
	"San Gontranno",
	"San Gottardo di Hildesheim",
	"San Graziano di Tours",
	"San Gregorio Barbarigo",
	"San Gregorio Grassi",
	"San Gregorio Illuminatore",
	"San Gregorio Taumaturgo",
	"San Gregorio di Langres",
	"San Gregorio di Narek",
	"San Gregorio di Nazianzo",
	"San Gregorio di Nissa",
	"San Gregorio di Tours",
	"San Gualtero",
	"San Guglielmo d'Aquitania",
	"San Guglielmo da Vercelli",
	"San Guglielmo di Malavalle",
	"San Guido Maria Conforti",
	"San Guido di Anderlecht",
	"San Guido di Pomposa",
	"San Jenaro Sanchez Delgadillo",
	"San John Henry Newman",
	"San Jose Isabel Flores Varela",
	"San Josef Freinademetz",
	"San JosemarÃ­a EscrivÃ¡ de Balaguer",
	"San Josep Manyanet y Vives",
	"San JosÃ© MarÃ­a Robles Hurtado",
	"San JosÃ© SÃ¡nchez del RÃ­o",
	"San JosÃ© de Anchieta",
	"San Juan Diego Cuauhtlatoatzin",
	"San Juan Grande RomÃ¡n",
	"San Juan del Castillo",
	"San JÃ³zef Bilczewski",
	"San Kevin",
	"San Ladislao",
	"San Lanfranco di Pavia",
	"San Lazzaro di Betania",
	"San Lazzaro mendicante",
	"San Leandro di Siviglia",
	"San Leodegario di Autun",
	"San Leonardo Murialdo",
	"San Leonardo da Porto Maurizio",
	"San Leonardo di Noblac",
	"San Leone di Catania",
	"San Leopoldo da Castelnuovo",
	"San Lidano da Sezze",
	"San Lodovico Pavoni",
	"San Lorenzo Giustiniani",
	"San Lorenzo Imbert",
	"San Lorenzo O'Toole",
	"San Lorenzo Ruiz",
	"San Lorenzo da Brindisi",
	"San Lorenzo di Canterbury",
	"San Lorenzo",
	"San Luca di Demenna",
	"San Luca di MelicuccÃ ",
	"San Luca di Messina",
	"San Luca evangelista",
	"San Luca il Giovane",
	"San Lucio di Cavargna",
	"San Lucio di Cirene",
	"San Ludgero di Munster",
	"San Ludolfo di Ratzeburg",
	"San Ludovico d'AngiÃ²",
	"San Ludovico da Casoria",
	"San Ludovico",
	"San Luigi Gonzaga",
	"San Luigi Guanella",
	"San Luigi Maria Grignion de Montfort",
	"San Luigi Orione",
	"San Luigi Scrosoppi",
	"San Luigi Versiglia",
	"San Luis BeltrÃ¡n",
	"San Lupicino",
	"San Lussorio",
	"San Macario il Grande",
	"San Magno",
	"San Maiolo",
	"San Malachia",
	"San Manaen",
	"San Manuel GonzÃ¡lez GarcÃ­a",
	"San Marcellino Champagnat",
	"San Marcellino di Ancona",
	"San Marciano",
	"San Marco evangelista",
	"San Marino diacono",
	"San Mario di Avenches",
	"San Marone martire",
	"San Marone",
	"San Martino de Porres",
	"San Martino di Braga",
	"San Martino di Tours",
	"San Marziale di Limoges",
	"San Massimiano di Ravenna",
	"San Massimiliano Maria Kolbe",
	"San Massimo d'Aveia",
	"San Massimo di Torino",
	"San Massimo il Confessore",
	"San Materno",
	"San Matteo Correa Magallanes",
	"San Matteo",
	"San Mattia apostolo",
	"San Maurilio di Angers",
	"San Maurizio",
	"San Mauro di Cesena",
	"San Mauro",
	"San Medardo",
	"San Melezio di Antiochia",
	"San Melitone di Sardi",
	"San Mellito di Canterbury",
	"San Mena di Costantinopoli",
	"San Mercuriale",
	"San Metodio I",
	"San Metodio di Olimpo",
	"San Metodio",
	"San Michel GaricoÃ¯ts",
	"San Michele Febres Cordero",
	"San Michele arcangelo",
	"San Miniato di Firenze",
	"San Mirocle di Milano",
	"San Modeste Andlauer",
	"San MosÃ¨ di Roma",
	"San MosÃ¨ l'Etiope",
	"San Muziano Maria Wiaux",
	"San Natale Chabanel",
	"San Nicasio di Reims",
	"San Niceta il Goto",
	"San Nicola Owen",
	"San Nicola Studita",
	"San Nicola da Tolentino",
	"San Nicola di Bari",
	"San Nicola di Flue",
	"San NicÃ¡nore",
	"San Nilo da Rossano",
	"San Nimatullah Youssef Kassab Al-Hardini",
	"San Nonnoso sul Monte Soratte",
	"San Norberto di Magdeburgo",
	"San Nuno Ãlvares Pereira",
	"San Ottone Frangipane",
	"San Pacifico da Sanseverino Marche",
	"San Pacomio",
	"San Palladio di Saintes",
	"San Pammachio",
	"San Pancrazio",
	"San Paolino II",
	"San Paolino di Nola",
	"San Paolino di York",
	"San Paolo Aureliano di Leon",
	"San Paolo Chong Ha-sang",
	"San Paolo I",
	"San Paolo Miki",
	"San Paolo apostolo",
	"San Paolo della Croce",
	"San Paolo di Narbona",
	"San Paolo di Tebe",
	"San Paolo di Verdun",
	"San Paolo il Semplice",
	"San Papia di Gerapoli",
	"San Pasquale BaylÃ³n",
	"San Paterniano",
	"San Paterno di Vannes",
	"San Patrizio",
	"San Pedro Pascual",
	"San Pedro Poveda Castroverde",
	"San Pedro de San JosÃ© de Betancurt",
	"San Pelagio di Cordova",
	"San Pelagio di Emona",
	"San Pelagio di Laodicea",
	"San Pellegrino Laziosi",
	"San Perpetuo di Tours",
	"San Petronio di Bologna",
	"San Pier Damiani",
	"San Pierio",
	"San Pierre-Julien Eymard",
	"San Pietro Canisio",
	"San Pietro Chanel",
	"San Pietro Claver",
	"San Pietro Crisci da Foligno",
	"San Pietro Crisologo",
	"San Pietro Esqueda Ramirez",
	"San Pietro Favre",
	"San Pietro Fourier",
	"San Pietro I (Pappacarbone)",
	"San Pietro I di Alessandria",
	"San Pietro II di Tarantasia",
	"San Pietro Maubant",
	"San Pietro Nolasco",
	"San Pietro Regalado da Valladolid",
	"San Pietro Truong van Thi",
	"San Pietro Yi Ho-yong",
	"San Pietro Yu Tae-ch'ol",
	"San Pietro d'AlcÃ¡ntara",
	"San Pietro da Perugia",
	"San Pietro da Verona",
	"San Pietro il Venerabile",
	"San Pietro",
	"San Pio da Pietrelcina",
	"San Pirmino di Murbach",
	"San Placido",
	"San Policarpo",
	"San Pompilio Maria Pirrotti",
	"San Prosdocimo di Padova",
	"San Prospero d'Aquitania",
	"San Protasio Algisi",
	"San Provino di Como",
	"San PrÃ³coro",
	"San Quintino di Vermand",
	"San Quodvultdeus",
	"San Rabano Mauro",
	"San Rafael GuÃ­zar Valencia",
	"San Raffaele Arnaiz Baron",
	"San Raffaele arcangelo",
	"San Raimondo Nonnato",
	"San Raimondo di PeÃ±afort",
	"San Ranieri",
	"San Remigio di Reims",
	"San Riccardo Gwyn",
	"San Rinaldo di Nocera Umbra",
	"San Roberto Bellarmino",
	"San Roberto Southwell",
	"San Roberto di Molesme",
	"San Roberto di Newminster",
	"San Rocco Gonzalez de Santa Cruz",
	"San Rocco",
	"San Rodolfo Sherwin",
	"San Rodrigo di Cordova",
	"San Roman Adame Rosales",
	"San Romano di Condat",
	"San Romano il Melode",
	"San Romedio",
	"San Romolo di Genova",
	"San Romualdo",
	"San Ruffillo di Forlimpopoli",
	"San Rufino",
	"San Rumoldo di Mechelen",
	"San Ruperto di Salisburgo",
	"San Saba Archimandrita",
	"San Sabas Reyes Salazar",
	"San Salvatore da Horta",
	"San Sansone di Dol",
	"San Sebastiano",
	"San Secondo",
	"San Serafino da Montegranaro",
	"San Serapio",
	"San Sergio di RadoneÅ¾",
	"San Servazio",
	"San Severino Boezio",
	"San Severino",
	"San Severo di Treviri",
	"San Sidonio Apollinare",
	"San Sigeberto II",
	"San Sigfrido di Vaxjo",
	"San Sigiberto III il Giovane",
	"San Sigismondo Gorazdowski",
	"San Sila",
	"San Silvestro Guzzolini",
	"San Simeone Stilita il Giovane",
	"San Simeone Stilita il Vecchio",
	"San Simeone di Gerusalemme",
	"San Simeone il Nuovo Teologo",
	"San Simeone il giusto",
	"San Simone Stock",
	"San Simone apostolo",
	"San Simone da Lipnica",
	"San Simplicio di Olbia",
	"San Siro di Pavia",
	"San Sisinnio",
	"San Sofronio di Gerusalemme",
	"San Spiridione di Trimithonte",
	"San StanisÅ‚aw PapczyÅ„ski",
	"San Suitberto di Kaiserswerth",
	"San Sulpizio il Pio",
	"San Tarcisio",
	"San Teobaldo di Marly",
	"San Teodoro Studita",
	"San Teodoro di Amasea",
	"San Teodoro di Canterbury",
	"San Teodoro di Octoduro",
	"San Teodosio il Cenobiarca",
	"San Teodoto di Ancira",
	"San Teofane il Confessore",
	"San Teofilo da Corte",
	"San Teofilo di Antiochia",
	"San Terenziano",
	"San Thorlak",
	"San Ticone di Amato",
	"San Timone",
	"San Timoteo",
	"San Tito",
	"San Tiziano di Oderzo",
	"San Tommaso Becket",
	"San Tommaso Garnet",
	"San Tommaso Moro",
	"San Tommaso Placidi da Cori",
	"San Tommaso d'Aquino",
	"San Trofimo di Arles",
	"San Turibio Romo Gonzalez",
	"San Turibio de Mogrovejo",
	"San Valentiniano di Coira",
	"San Valentino",
	"San Valeriano di Aquileia",
	"San Valeriano di Avensano",
	"San Valeriano di ForlÃ¬",
	"San Venceslao",
	"San Verano di Cavaillon",
	"San Vigilio di Trento",
	"San Villibaldo di EichstÃ¤tt",
	"San Villibrordo",
	"San Villigiso di Magonza",
	"San Vincenzo Ferrer",
	"San Vincenzo Grossi",
	"San Vincenzo Madelgario",
	"San Vincenzo Maria Strambi",
	"San Vincenzo Pallotti",
	"San Vincenzo Romano",
	"San Vincenzo de' Paoli",
	"San Vincenzo di Lerino",
	"San Vincenzo di Saragozza",
	"San Virgilio di Arles",
	"San Virgilio di Salisburgo",
	"San Vitale d'Assisi",
	"San Vitale martire",
	"San Vitaliano da Capua",
	"San Vito",
	"San Vittore di Capua",
	"San Vittore il Moro",
	"San Volfango di Ratisbona",
	"San Volusiano di Tours",
	"San Wunibald di Heidenheim",
	"San Zaccaria (padre di Giovanni Battista)",
	"San Zeno",
	"San Zotico di Costantinopoli",
	"San Zygmunt SzczÄ™sny FeliÅ„ski",
	"Sant'Abbondio vescovo",
	"Sant'Abbone di Fleury",
	"Sant'Abercio di Geropoli",
	"Sant'Abo di Tiflis",
	"Sant'Abramo anacoreta",
	"Sant'Acacio di Militene",
	"Sant'Acardo",
	"Sant'Achilleo di Larissa",
	"Sant'Adalardo di Corbie",
	"Sant'Adalberto di Praga",
	"Sant'Adelaide",
	"Sant'Adelina di Mortain",
	"Sant'Adolfo di OsnabrÃ¼ck",
	"Sant'Adone di Vienne",
	"Sant'Adriano di Canterbury",
	"Sant'Aelredo di Rievaulx",
	"Sant'Agata",
	"Sant'Agatone (martire)",
	"Sant'Agnese d'Assisi",
	"Sant'Agnese da Montepulciano",
	"Sant'Agnese di Boemia",
	"Sant'Agnese di Roma",
	"Sant'Agostina Pietrantoni",
	"Sant'Agostino Roscelli",
	"Sant'Agostino Zhao Rong",
	"Sant'Agostino d'Ippona",
	"Sant'Agostino di Canterbury",
	"Sant'Agrippino di Napoli",
	"Sant'Aidano di Lindisfarne",
	"Sant'Ailbeo di Emly",
	"Sant'Airaldo di Saint-Jean-de-Maurienne",
	"Sant'Albano d'Inghilterra",
	"Sant'Alberico di CÃ®teaux",
	"Sant'Alberto Chmielowski",
	"Sant'Alberto Hurtado Cruchaga",
	"Sant'Alberto Magno",
	"Sant'Alberto da Genova",
	"Sant'Alberto degli Abbati",
	"Sant'Alberto di Butrio",
	"Sant'Alberto di Gerusalemme",
	"Sant'Alberto di Lovanio",
	"Sant'Alberto di Montecorvino",
	"Sant'Alberto di Pontida",
	"Sant'Albina",
	"Sant'Alessandro I",
	"Sant'Alessandro Sauli",
	"Sant'Alessandro di Alessandria",
	"Sant'Alessandro l'Acemeta",
	"Sant'Alessio di Roma",
	"Sant'Alferio",
	"Sant'Alfonsa dell'Immacolata Concezione",
	"Sant'Alfonso Maria Fusco",
	"Sant'Alfonso Maria de' Liguori",
	"Sant'Alfonso RodrÃ­guez",
	"Sant'Alfredo di Hildesheim",
	"Sant'Alipio (Stiliano) lo stilita",
	"Sant'Alonso Rodriguez martire",
	"Sant'Amabile di Rium",
	"Sant'Amando di Maastricht",
	"Sant'Amanzio di Como",
	"Sant'Amato di Remiremont",
	"Sant'Ambrogio di Milano",
	"Sant'Anania di Damasco",
	"Sant'Anastasia di Sirmio",
	"Sant'Anatalo",
	"Sant'Anatolio di Costantinopoli",
	"Sant'Anatolio di Laodicea",
	"Sant'Andrea Avellino",
	"Sant'Andrea Bobola",
	"Sant'Andrea Corsini",
	"Sant'Andrea Dung-Lac",
	"Sant'Andrea Kim Tae-gÅn",
	"Sant'Andrea apostolo",
	"Sant'AndrÃ© Bessette",
	"Sant'AndrÃ©-Hubert Fournet",
	"Sant'Anfilochio di Iconio",
	"Sant'Angela Merici",
	"Sant'Angela da Foligno",
	"Sant'Angela de la Cruz",
	"Sant'Angelo d'Acri",
	"Sant'Angelo da Gerusalemme",
	"Sant'Angilberto di Centula",
	"Sant'Annibale Maria Di Francia",
	"Sant'Ansano",
	"Sant'Anselmo d'Aosta",
	"Sant'Anselmo da Baggio",
	"Sant'Anselmo di Nonantola",
	"Sant'Antelmo di Chignin",
	"Sant'Antimo di Nicomedia",
	"Sant'Antipa di Pergamo",
	"Sant'Antonino Fantosati",
	"Sant'Antonino Pierozzi",
	"Sant'Antonio Maria Gianelli",
	"Sant'Antonio Maria Pucci",
	"Sant'Antonio Maria Zaccaria",
	"Sant'Antonio MarÃ­a Claret y ClarÃ¡",
	"Sant'Antonio Pecierskij",
	"Sant'Antonio abate",
	"Sant'Antonio di LÃ©rins",
	"Sant'Antonio di Padova",
	"Sant'Antonio di Sant'Anna GalvÃ£o",
	"Sant'Apollinare di Ravenna",
	"Sant'Apollo",
	"Sant'Apollonia",
	"Sant'Arcangelo Tadini",
	"Sant'Archippo di Colossi",
	"Sant'Aredio di Limoges",
	"Sant'Arialdo di Milano",
	"Sant'Aristarco",
	"Sant'Aristide Marciano",
	"Sant'Armentario di Pavia",
	"Sant'Arnoldo Janssen",
	"Sant'Arnolfo di Metz",
	"Sant'Arnolfo di Soissons",
	"Sant'Arsenio il Grande",
	"Sant'Artaldo di Belley",
	"Sant'Aspreno di Napoli",
	"Sant'Atanasio Bazzekuketta",
	"Sant'Atanasio il Grande",
	"Sant'Atanasio l'Atonita",
	"Sant'Atenagora di Atene",
	"Sant'Atenogene di Sebaste",
	"Sant'Augusto Chapdelaine",
	"Sant'Aureliano di Arles",
	"Sant'Aurelio di Cartagine",
	"Sant'Aussenzio",
	"Sant'Austremonio",
	"Sant'Ebrulfo di Ouche",
	"Sant'Edmondo Arrowsmith",
	"Sant'Edmondo Campion",
	"Sant'Edmondo di Canterbury",
	"Sant'Edmondo",
	"Sant'Edvige di Andechs",
	"Sant'Edvige di Polonia",
	"Sant'Edwin",
	"Sant'Egesippo",
	"Sant'Egidio Maria di San Giuseppe",
	"Sant'Egidio",
	"Sant'Eldrado di Novalesa",
	"Sant'Elena imperatrice",
	"Sant'Eleuterio di Tournai",
	"Sant'Elfego di Canterbury",
	"Sant'Elia Facchini",
	"Sant'Elia di Enna",
	"Sant'Eligio di Noyon",
	"Sant'Elisabetta (madre di Giovanni Battista)",
	"Sant'Elisabetta Anna Bayley Seton",
	"Sant'Elisabetta d'Ungheria",
	"Sant'Elisabetta del Portogallo",
	"Sant'Elisabetta della TrinitÃ ",
	"Sant'Ellero",
	"Sant'Emerenziana",
	"Sant'Emerico d'Ungheria",
	"Sant'Emeterio",
	"Sant'Emidio",
	"Sant'Emilia Maria Guglielma de Rodat",
	"Sant'Emilia de Vialar",
	"Sant'Emiliano I di Vercelli",
	"Sant'Emiliano della Cogolla",
	"Sant'Enrico II",
	"Sant'Enrico Morse",
	"Sant'Enrico de Osso y Cervello",
	"Sant'Enrico di Uppsala",
	"Sant'Epifanio di Pavia",
	"Sant'Epifanio di Salamina",
	"Sant'Erardo di Ratisbona",
	"Sant'Erasmo",
	"Sant'Erchembodone di ThÃ©rouanne",
	"Sant'Ercolano di Perugia",
	"Sant'Eriberto di Colonia",
	"Sant'Eric IX",
	"Sant'Erveo",
	"Sant'Etelberto",
	"Sant'Ethelwold di Winchester",
	"Sant'Eucherio di Lione",
	"Sant'Eufrasia del Sacro Cuore di GesÃ¹",
	"Sant'Euplo",
	"Sant'Euprepio di Verona",
	"Sant'Eusebio di Milano",
	"Sant'Eusebio di Vercelli",
	"Sant'Eustachio Placido",
	"Sant'Eustasio",
	"Sant'Eustochia Calafato",
	"Sant'Eustorgio di Milano",
	"Sant'Eutichio",
	"Sant'Eutimio",
	"Sant'Everardo del Friuli",
	"Sant'Ezequiel Moreno y DÃ­az",
	"Sant'Ida di Herzfeld",
	"Sant'Idulfo di Moyenmoutier",
	"Sant'Ignazio Clemente Delgado",
	"Sant'Ignazio I di Costantinopoli",
	"Sant'Ignazio da Laconi",
	"Sant'Ignazio da SanthiÃ ",
	"Sant'Ignazio di Antiochia",
	"Sant'Ignazio di Loyola",
	"Sant'Ilario di Arles",
	"Sant'Ilario di Poitiers",
	"Sant'Ilarione di Gaza",
	"Sant'Ildefonso da Toledo",
	"Sant'Ildegarda di Bingen",
	"Sant'Iltrude di Liessies",
	"Sant'Iltuto",
	"Sant'Innocenzo Canoura Arnau",
	"Sant'Ippolito di Roma",
	"Sant'Ireneo di Lione",
	"Sant'Isacco Jogues",
	"Sant'Isidoro di Pelusio",
	"Sant'Isidoro di Siviglia",
	"Sant'Isidoro l'agricoltore",
	"Sant'Ivo di Chartres",
	"Sant'Obizio da Niardo",
	"Sant'Oddone di Cluny",
	"Sant'Odilia di Hohenbourg",
	"Sant'Olav",
	"Sant'Olga di Kiev",
	"Sant'Oliviero Plunkett",
	"Sant'Onesiforo",
	"Sant'Onesimo",
	"Sant'Onofrio",
	"Sant'Onorato di Arles",
	"Sant'Onorato di Milano",
	"Sant'Onorio di Canterbury",
	"Sant'Orso di Aosta",
	"Sant'Orsola e compagne",
	"Sant'Oscar di Brema",
	"Sant'Osvaldo di Northumbria",
	"Sant'Osvaldo di Worcester",
	"Sant'Otmar di San Gallo",
	"Sant'Ottato di Milevi",
	"Sant'Ubaldesca Taccini",
	"Sant'Ubaldo Baldassini",
	"Sant'Ugo da Genova",
	"Sant'Ugo di Cluny",
	"Sant'Ugo di Grenoble",
	"Sant'Ugo di Lincoln",
	"Sant'Ulderico di Augusta",
	"Sant'Umile da Bisignano",
	"Sant'Ursicino del Giura",
	"Sant'Ã“scar Romero",
	"Santi Aquila e Priscilla",
	"Santi Avventore, Ottavio e Solutore",
	"Santi Cirillo e Metodio",
	"Santi Cosma e Damiano",
	"Santi Crispino e Crispiniano",
	"Santi Felice, Regola ed Essuperanzio",
	"Santi Gervasio e Protasio",
	"Santi Gioacchino e Anna",
	"Santi Giovanni e Paolo",
	"Santi Marcellino e Pietro",
	"Santi Martiri di Gorcum",
	"Santi Primi martiri della santa Chiesa di Roma",
	"Santi Quattro Coronati",
	"Santi martiri coreani",
	"Santi martiri di Otranto",
	"Santi martiri scillitani",
	"Santi martiri vietnamiti",
	"Santo Stefano Harding",
	"Santo Stefano Minicillo",
	"Santo Stefano Teodoro CuÃ©not",
	"Santo Stefano d'Ungheria",
	"Santo Stefano di ChÃ¢tillon",
	"Santo Stefano di Grandmont",
	"Santo Stefano il Giovane",
	"Santo Stefano",
	"Santo Sturmio di Fulda",
	"Sergio I",
	"Sette santi fondatori",
	"Tichico",
	"Tommaso da Villanova",
	"Tutti i Santi",
	"Wilhelm von Hirsau",
	"Zaccaria (profeta)",
	"Zaccheo"
];
function getRandomSanto () {
    var indexsanto= Math.floor(Math.random() * (santi.length));
    return santi[indexsanto];
}
var nomi = [
	"il bugiardo",
	"il criminale",
	"il ladro",
	"il porco",
	"il maiale",
	"lo scomunicato",
	"il babbeo",
	"il bacucco",
	"il barbaro",
	"il becero",
	"il beota",
	"il bigotto",
	"il bizoco",
	"il bizzoco",
	"il boss",
	"il bullo",
	"il burino",
	"il buttero",
	"il buzzurro",
	"il cafone",
	"il cattivo",
	"il citrullo",
	"il contadino",
	"il cretino",
	"il debosciato",
	"il grullo",
	"l'idiota",
	"l'imbecille",
	"il malvagio",
	"il mamalucco",
	"il mamelucco",
	"il mammalucco",
	"il matusa",
	"l'osceno",
	"l'ozioso",
	"il pagano",
	"il pacchiano",
	"il pazzo",
	"lo scemo",
	"lo schifoso",
	"lo sciocco",
	"il secchione",
	"il selvaggio",
	"lo stolto",
	"lo stupido",
	"il sudicio",
	"il tamarro",
	"il villano",
	"il volgare",
	"lo zitello",
	"lo zotico",
	"lo scostumato"
];
function getRandomNome () {
    var indexnomi= Math.floor(Math.random() * (nomi.length));
    return nomi[indexnomi];
}
var aggettivi = [
	"bastardo",
	"fascista",
	"nazista",
	"bestemmiatore",
	"pedofilo",
	"razzista",
	"anarchico",
	"traditore",
	"meschino",
	"maldestro",
	"inospitale",
	"scorbutico",
	"ripugnante",
	"inaffidabile",
	"malinconico",
	"egoista",
	"odioso",
	"rinunciatario",
	"ostile",
	"sprezzante",
	"apatico",
	"sdegnato",
	"timido",
	"stonato",
	"ingenuo",
	"disattento",
	"trepido",
	"sventato",
	"brutto",
	"scontroso",
	"cattivo",
	"malvagio",
	"irrequieto",
	"incapace",
	"arrendevole",
	"repellente",
	"spento",
	"taciturno",
	"misterioso",
	"incoerente",
	"rozzo",
	"spietato",
	"invidioso",
	"intransigente",
	"incompreso",
	"bizzarro",
	"distratto",
	"collerico",
	"sconosciuto",
	"incontentabile",
	"scontento",
	"fifone",
	"burbero",
	"scorretto",
	"scortese",
	"lunatico",
	"scialbo",
	"indifferente",
	"indeciso",
	"incerto",
	"statico",
	"sfacciato",
	"invadente",
	"goffo",
	"indisponibile",
	"noioso",
	"violento",
	"maleducato",
	"rigido",
	"trasandato",
	"fiacco",
	"frigido",
	"superficiale",
	"introverso",
	"squilibrato",
	"infedele",
	"infelice",
	"traditore",
	"diffidente",
	"geloso",
	"sfigato",
	"debole",
	"sfortunato",
	"fragile",
	"minchione",
	"codardo",
	"sgarbato",
	"meschino",
	"scortese",
	"triste",
	"mesto",
	"sbagliato",
	"sgradevole",
	"sgraziato",
	"inidoneo",
	"pauroso",
	"emotivo",
	"inutile",
	"prevedibile",
	"orribile",
	"vendicativo",
	"inetto",
	"pericoloso",
	"stupido",
	"insignificante",
	"disinteressato",
	"ignorante",
	"ozioso",
	"sleale",
	"occupato",
	"taciturno",
	"avaro",
	"immaturo",
	"smemorato",
	"negligente",
	"crudele",
	"aggressivo",
	"vanitoso",
	"strano",
	"eccentrico",
	"disubbidiente",
	"disonesto",
	"pigro",
	"disordinato",
	"disorganizzato",
	"dimesso",
	"copione",
	"impertinente",
	"pessimista",
	"litigioso",
	"cinico",
	"impaziente",
	"imperfetto",
	"sconsiderato",
	"fastidioso",
	"negativo",
	"impotente",
	"inesperto",
	"disfattista",
	"spregevole",
	"noncurante",
	"impreparato",
	"puzzolente",
	"imprudente",
	"sporco",
	"ritardatario",
	"falso",
	"addolorato",
	"grezzo",
	"afflitto",
	"scriteriato",
	"irrazionale",
	"sognatore",
	"irregolare",
	"irresponsabile",
	"povero",
	"ingrato",
	"impulsivo",
	"contratto",
	"svergognato",
	"insolente",
	"freddo",
	"avventato",
	"pazzo",
	"serioso",
	"enigmatico",
	"insensato",
	"insensibile",
	"turbato",
	"insicuro",
	"antipatico",
	"bugiardo",
	"asociale",
	"solitario",
	"insoddisfatto",
	"timoroso",
	"impacciato",
	"oscuro",
	"sedentario",
	"vagabondo",
	"disprezzato",
	"solito",
	"saccente",
	"inferiore",
	"stordito",
	"agitato",
	"esigente",
	"ribelle",
	"presuntuoso",
	"comune",
	"vigliacco",
	"lento",
	"lontano",
	"perdente",
	"viziato",
	"svogliato",
	"testardo",
	"pallido",
	"basso",
	"gracile",
	"sbarbato",
	"calvo/rasato",
	"peloso",
	"massiccio",
	"vecchio",
	"paffuto",
	"femminile",
	"spettinato",
	"ciccione",
	"scheletrico",
	"malato",
	"grasso",
	"accigliato",
	"sovrappeso",
	"insano"
];
function getRandomAggettivo () {
     var indexagg= Math.floor(Math.random() * (aggettivi.length));
     return aggettivi[indexagg];
}
var santi_render = document.getElementById('santi');
function santifica () {
	santi_render.innerHTML = getRandomSanto() + " " + getRandomNome() + " " + getRandomAggettivo();
}
};
